In [1]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle
import cv2

In [2]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
print(face_cascade)

<CascadeClassifier 0x7f3c9427e330>


In [3]:
 def face_extract(img):
    gray= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    if faces is ():
        return None
    
    for (x,y,w,h) in faces:
        cropped=img[y:y+h, x:x+w]
    
    return cropped


In [7]:
cap=cv2.VideoCapture(0)
count=0
while(True):
    ret, frame=cap.read()
    if face_extract(frame) is not None:
        count+=1
        
        img= cv2.resize(face_extract(frame), (200,200))
        #img= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        
        file_name_path='./Faces/Kashish/'+str(count)+'.jpg'
        cv2.imwrite(file_name_path, img)
        
        cv2.putText(img, str(count), (50,50), cv2.FONT_HERSHEY_COMPLEX, 1,(0,255,0),2)
        cv2.imshow('image',img)
        if cv2.waitKey(13)& 0xFF == ord('q'):
            break
        
    if count==1000:
        break
        
cap.release()
cv2.destroyAllWindows()

In [4]:
train=[]
label=[]
names=[ 'Kashish', 'Rakshit', 'Aditya']
for name in names:
    for i in range(1,100):       
        photo=cv2.imread('./Faces/'+name+'/'+ str(i)+'.jpg')
        train.append(np.asarray(photo))
        label.append(name)
 

In [5]:
data=pd.DataFrame({'input':train, 'label':label})
data['label']=label
df = data.sample(frac=1).reset_index(drop=True)

In [6]:
y=np.array(df['label'])
y.shape

(297,)

In [7]:
z=[]
for i in range(df.shape[0]):
    z.append(df['input'][i])
z=np.array(z)
z.shape
#z.reshape(267,200,200)
#print(z)

(297, 200, 200, 3)

In [8]:
print(z.shape)

(297, 200, 200, 3)


In [9]:
X_train= z[:230]
X_train=X_train/255
X_test=z[230:]
X_test=X_test/255
y_train= y[:230]
y_test=y[230:]

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(230, 200, 200, 3)
(67, 200, 200, 3)
(230,)
(67,)


# Model Building

In [11]:
import keras
import time

Using TensorFlow backend.


In [12]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
from keras.callbacks import TensorBoard

In [14]:
names=['Kashish', 'Aditya', 'Rakshit']

In [15]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(names)
print(integer_encoded)

[1 0 2]


In [16]:
y_tr=label_encoder.transform(y_train)
y_te=label_encoder.transform(y_test)
print(y_tr)

[1 0 1 0 1 2 0 2 2 0 1 1 2 1 1 1 1 1 0 2 0 0 2 2 0 2 0 0 1 1 2 1 2 0 1 1 2
 2 1 1 0 1 1 0 0 2 1 0 0 2 1 2 2 0 2 0 2 0 2 2 0 0 2 2 2 0 2 0 1 1 0 2 0 2
 0 1 1 2 0 2 0 2 1 1 2 0 0 0 1 1 0 0 2 2 0 1 1 1 1 2 0 0 1 0 0 1 0 2 2 0 2
 0 2 0 1 0 2 0 1 2 1 0 2 2 1 2 0 0 0 0 1 2 0 0 2 2 1 2 1 0 2 1 2 2 0 1 0 2
 0 1 1 1 0 0 0 1 2 2 1 1 2 0 1 2 0 1 0 2 0 1 2 2 0 2 1 1 1 0 2 2 1 1 1 2 0
 1 2 1 2 0 2 0 0 1 2 0 1 0 0 0 1 1 0 1 0 0 1 1 1 2 2 2 1 1 0 0 2 0 0 2 1 2
 0 2 0 2 2 0 0 2]


In [17]:
from keras.utils import to_categorical
y_binary = to_categorical(y_tr)
#print(y_binary)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0.

In [37]:
model=Sequential()
name='cnn-{}'.format(int(time.time()))
model.add(Conv2D(64, (3,3), input_shape=(200,200,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(3, activation='sigmoid'))
tensorboard = TensorBoard(log_dir="logs/{}".format(name))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])
model.fit(X_train, y_binary, batch_size=32, epochs=5, validation_split=0.3, callbacks=[tensorboard])

Train on 161 samples, validate on 69 samples
Epoch 1/5
161/161 [==============================] - 11s 66ms/step - loss: 1.5354 - acc: 0.3665 - val_loss: 1.0648 - val_acc: 0.3188
Epoch 2/5
161/161 [==============================] - 10s 65ms/step - loss: 0.8918 - acc: 0.3913 - val_loss: 1.2836 - val_acc: 0.6812
Epoch 3/5
161/161 [==============================] - 11s 65ms/step - loss: 0.6240 - acc: 0.7329 - val_loss: 0.1019 - val_acc: 1.0000
Epoch 4/5
161/161 [==============================] - 10s 65ms/step - loss: 0.0610 - acc: 1.0000 - val_loss: 0.1216 - val_acc: 0.9420
Epoch 5/5
161/161 [==============================] - 11s 67ms/step - loss: 0.0595 - acc: 0.9689 - val_loss: 0.0034 - val_acc: 1.0000


In [35]:
ans=model.predict(X_test)

In [36]:
print(ans)

[[1.15036964e-05 1.00000000e+00 1.00000000e+00]
 [7.80820847e-06 1.00000000e+00 1.00000000e+00]
 [1.54376030e-05 1.00000000e+00 1.00000000e+00]
 [4.76837158e-07 1.00000000e+00 9.99999881e-01]
 [7.33137131e-06 1.00000000e+00 1.00000000e+00]
 [9.77516174e-06 1.00000000e+00 1.00000000e+00]
 [4.47034836e-07 1.00000000e+00 9.99999940e-01]
 [1.31130219e-06 1.00000000e+00 9.99999881e-01]
 [1.42753124e-05 1.00000000e+00 1.00000000e+00]
 [2.93850899e-05 1.00000000e+00 9.99997318e-01]
 [1.29938126e-05 1.00000000e+00 1.00000000e+00]
 [9.97337699e-01 1.00000000e+00 1.00000000e+00]
 [9.98436689e-01 1.00000000e+00 1.00000000e+00]
 [9.97268558e-01 1.00000000e+00 1.00000000e+00]
 [9.98427033e-01 1.00000000e+00 1.00000000e+00]
 [9.89437103e-06 1.00000000e+00 1.00000000e+00]
 [9.94251668e-01 1.00000000e+00 1.00000000e+00]
 [1.90734863e-06 1.00000000e+00 1.00000000e+00]
 [1.43051147e-06 1.00000000e+00 9.99999762e-01]
 [7.45058060e-07 1.00000000e+00 9.99999881e-01]
 [4.14252281e-06 1.00000000e+00 1.000000

In [27]:
from sklearn.metrics import accuracy_score

In [29]:
#print(accuracy_score(ans, y_test))

In [21]:
dense_layers=[0,1,2]
layer_sizes= [32, 64, 128]
conv_layers=[1,2,3]

for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for conv_layer in conv_layers:
            name= "{}- conv-{}-nodes- {}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            print("********************* "+name+" ************************")  
            
            model=Sequential()
            model.add(Conv2D(layer_size, (3,3), input_shape=X_train.shape[1:], activation='relu'))
            model.add(MaxPooling2D(pool_size=(2,2)))
            
            for i in range(conv_layer-1):
                model.add(Conv2D(layer_size, (3,3), activation='relu'))
                model.add(MaxPooling2D(pool_size=(2,2)))
                
            model.add(Flatten())
            for i in range(dense_layer):
                model.add(Dense(layer_size, activation='relu'))
            
            model.add(Dense(3, activation='softmax')) 
            tensorboard = TensorBoard(log_dir="logs/{}".format(name))
            model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])
            model.fit(X_train, y_binary, batch_size=32, epochs=10, validation_split=0.3, callbacks=[tensorboard])

SyntaxError: invalid syntax (<ipython-input-21-8064839cafde>, line 27)

In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 198, 198, 64)      1792      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 99, 99, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 97, 97, 64)        36928     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 48, 48, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 147456)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                9437248   
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 195       
Total para